name: .NET Blazor Build and Publish Artifact

# Trigger the workflow manually
on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest  # Define the runner environment (Ubuntu)

    # Define environment variables
    env:
      DOTNET_HOME: "/usr/bin/dotnet"
      DOTNET_VERSION: "8.0"
      DOTNET_RUNTIME: "net8.0"
      APP_NAME: "BlazorApp1"
      BUILD_CONFIGURATION: "Release"
      DOTNET_PATH: "/home/abubakar/java/dot-net/dotnet-blazor/BlazorApp1/bin/Release/net8.0"

    steps:
      # Step 1: Checkout the code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up .NET SDK
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Step 3: Restore NuGet packages
      - name: Restore dependencies
        run: dotnet restore $APP_NAME

      # Step 4: Build the application
      - name: Build the application
        run: dotnet build $APP_NAME --configuration $BUILD_CONFIGURATION

      # Step 5: Publish the application as an artifact
      - name: Publish the application
        run: dotnet publish $APP_NAME --configuration $BUILD_CONFIGURATION --output $DOTNET_PATH

      # Step 6: Upload the artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: blazor-app-artifact
          path: ${{ env.DOTNET_PATH }}
